name: Jekyll Build with Folder Preservation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Specify the Ruby version
          bundler-cache: true

      # Restore previous build if it exists
      - name: Restore Previous Build
        uses: actions/download-artifact@v3
        with:
          name: site
        continue-on-error: true

      # Install dependencies
      - name: Install Dependencies
        run: |
          bundle install

      # Build Jekyll site
      - name: Build Jekyll Site
        run: |
          # Copy old folder contents if exists
          cp -r _site/_clusters ./_clusters || true
          # Build site excluding the folder
          bundle exec jekyll build
          # Restore the excluded folder into the built site
          cp -r ./_clusters _site/_clusters

      # Upload updated site as an artifact
      - name: Upload Site Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site
